<?php

namespace Database\Seeders;

use App\Models\Faculty;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class FacultySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $faculties = [
            [
                'faculty_id' => '1',
                'first_name' => 'Hobert',
                'middle_name' => 'A.',
                'last_name' => 'Abrigana',
                'position' => 'Instructor',
                'designation' => 'BSCS Program Head',
                'email' => 'jmmlurzano00587@usep.edu.ph',
                'orcid' => null,
                'contact_number' => '(082) 227-8192 local 249',
                'educational_attainment' => 'Bachelor of Science in Computer Science (BSCS), Master in Information Management (MIM)',
                'field_of_specialization' => 'Database Management System, Software Application, Development of IS plan',
                'research_interest' => 'Business Data Modeling',
            ],
            [
                'faculty_id' => '2',
                'first_name' => 'Cheryl',
                'middle_name' => 'R.',
                'last_name' => 'Amante',
                'position' => 'Instructor',
                'designation' => 'Extension Head',
                'email' => 'cramante@usep.edu.ph',
                'orcid' => '0000-0002-5686-2684',
                'contact_number' => '(082) 227-8192 local 249',
                'educational_attainment' => 'Bachelor of Science in Computer Science (BSCS), Master in Information Management (MIM)',
                'field_of_specialization' => 'Database Management System, Software Application, Development of IS plan',
                'research_interest' => 'Business Data Modeling',
            ],
            [
                'faculty_id' => '3',
                'first_name' => 'Annacel',
                'middle_name' => 'B.',
                'last_name' => 'Delima',
                'position' => 'Instructor',
                'designation' => 'Head, CED and SOL Library',
                'email' => 'annacel.delima@usep.edu.ph',
                'orcid' => '0000-0003-0091-3929',
                'contact_number' => '(082) 227-8192 local 249',
                'educational_attainment' => 'Bachelor of Library and Information Science (BLIS), Master of Science in Library and Information Science (MSLIS)',
                'field_of_specialization' => 'Library Science',
                'research_interest' => 'Library and Information Science',
            ],
            [
                'faculty_id' => '4',
                'first_name' => 'Cristina',
                'middle_name' => 'E.',
                'last_name' => 'Dumdumaya',
                'position' => 'Professor',
                'designation' => 'Director, PMMED',
                'email' => 'cedumdumaya@usep.edu.ph',
                'orcid' => '0000-0003-2148-5003',
                'contact_number' => '(082) 227-8192 local 249',
                'educational_attainment' => 'Bachelor of Science in Computer Engineering, Master of Arts in Teaching College Physics, Master\'s in Information Technology, Graduate Diploma in Computer Science, PhD in Computer Science',
                'field_of_specialization' => 'Artificial Intelligence in Education, Data Science, Digital Image Processing, Software Engineering',
                'research_interest' => 'Machine Learning, Data Mining, Systems Analysis and Design',
            ],
            [
                'faculty_id' => '5',
                'first_name' => 'Gresiel',
                'middle_name' => 'E.',
                'last_name' => 'Ferrando',
                'position' => 'Assistant Professor',
                'designation' => 'BLIS Program Head / MLIS Program Head',
                'email' => 'gresielferrando@usep.edu.ph',
                'orcid' => null,
                'contact_number' => '(082) 227-8192 local 249',
                'educational_attainment' => 'Bachelor of Arts in Literature, Bachelor of Library and Information Science – earned units, Master of Science in Library and Information Science',
                'field_of_specialization' => 'Information Literacy, Collection Development, Information Resources and Services, Web Technologies, Library Quality Assurance, LIS Education',
                'research_interest' => 'Collection Analysis, Document Management, Research, Indexing, Abstracting',
            ],
            [
                'faculty_id' => '6',
                'first_name' => 'Randy',
                'middle_name' => 'S.',
                'last_name' => 'Gamboa',
                'position' => 'Professor',
                'designation' => 'CIC Faculty Association President',
                'email' => 'rsgamboa@usep.edu.ph',
                'orcid' => '0000-0002-1098-7772',
                'contact_number' => '(082) 227-8192 local 249',
                'educational_attainment' => 'Master in Environmental Planning, Master Science in Computer Science, PhD in Educational Leadership',
                'field_of_specialization' => 'Information Systems Leadership and Governance, Educational Technology, Data Privacy and Security',
                'research_interest' => 'Data Privacy and Security, Information Systems',
            ],
            [
                'faculty_id' => '7',
                'first_name' => 'Marvin',
                'middle_name' => 'S.',
                'last_name' => 'Lagmay',
                'position' => 'Instructor',
                'designation' => null,
                'email' => 'marvin@usep.edu.ph',
                'orcid' => '0000-0002-0090-3045',
                'contact_number' => '(082) 227-8192 local 249',
                'educational_attainment' => 'Bachelor in Computer Technology, Teacher Certificate for Non-Education Professionals',
                'field_of_specialization' => 'Educational Technology, Instructional Design, Interaction Design',
                'research_interest' => 'Educational Technology Integration',
            ],
            [
                'faculty_id' => '8',
                'first_name' => 'Ivy Kim',
                'middle_name' => 'D.',
                'last_name' => 'Machica',
                'position' => 'Associate Professor',
                'designation' => 'Dean',
                'email' => 'ikmachica@usep.edu.ph',
                'orcid' => '0000-0002-2708-6305',
                'contact_number' => '(082) 227-8192 local 249',
                'educational_attainment' => 'Bachelor of Science in Computer Science, Master of Science in Information Science, Doctor in Information Technology',
                'field_of_specialization' => 'Computer Science, Information Technology',
                'research_interest' => 'Artificial Intelligence and Internet of Things (IoT)',
            ],
            [
                'faculty_id' => '9',
                'first_name' => 'Michael',
                'middle_name' => 'V.',
                'last_name' => 'Machica',
                'position' => 'Associate Professor',
                'designation' => 'Deputy Director, IPMU',
                'email' => 'michael.machica@usep.edu.ph',
                'orcid' => null,
                'contact_number' => '(082) 227-8192 local 249',
                'educational_attainment' => null,
                'field_of_specialization' => null,
                'research_interest' => null,
            ],
            [
                'faculty_id' => '10',
                'first_name' => 'Tamara Cher',
                'middle_name' => 'R.',
                'last_name' => 'Mercado',
                'position' => 'Professor',
                'designation' => 'Vice President for Planning and Quality Assurance',
                'email' => 'tammy@usep.edu.ph',
                'orcid' => '009-0001-9731-9987',
                'contact_number' => '(082) 227-8192 local 249',
                'educational_attainment' => 'Bachelor of Science in Computer Engineering, Master of Science in Information Science, PhD in Information Technology',
                'field_of_specialization' => 'Information Technology',
                'research_interest' => 'Information Systems, Knowledge Management, eLearning, Digital Processing',
            ],
            [
                'faculty_id' => '11',
                'first_name' => 'Cindy',
                'middle_name' => 'S.',
                'last_name' => 'Moldes',
                'position' => 'Instructor',
                'designation' => 'Faculty Librarian',
                'email' => 'cindy.moldes@usep.edu.ph',
                'orcid' => null,
                'contact_number' => '(082) 227-8192 local 249',
                'educational_attainment' => 'Bachelor of Science in Library and Information Science, Master of Science in Library and Information Science',
                'field_of_specialization' => 'Library and Information Science',
                'research_interest' => 'Library and Information Science',
            ],
            [
                'faculty_id' => '12',
                'first_name' => 'Nancy',
                'middle_name' => 'S.',
                'last_name' => 'Mozo',
                'position' => 'Assistant Professor',
                'designation' => 'BSIT Program Head',
                'email' => 'nancy.mozo@usep.edu.ph',
                'orcid' => '0009-0005-5074-4651',
                'contact_number' => '(082) 227-8192 local 249',
                'educational_attainment' => 'Bachelor of Science in Information Technology, Master of Information Technology',
                'field_of_specialization' => 'Mobile Frameworks and Development, Computer, Networks, Database Management',
                'research_interest' => 'Networking, Web Development, Multimedia Design',
            ],
            [
                'faculty_id' => '13',
                'first_name' => 'Eula Mae',
                'middle_name' => 'N.',
                'last_name' => 'Templa',
                'position' => 'Instructor',
                'designation' => 'Head, College of Technology LRC and STLRC',
                'email' => 'eula.nabong@usep.edu.ph',
                'orcid' => '0000-0003-1323-9742',
                'contact_number' => '(082) 227-8192 local 249',
                'educational_attainment' => 'Bachelor of Library and Information Science, Master of Science in Library and Information Science',
                'field_of_specialization' => 'Archives and Preservation, Record Management, Archival Science',
                'research_interest' => 'Cultural Informatics and Heritage, Information Retrieval, Libraries and Librarianship, Organization of Knowledge and Information, Youth Literature, Culture, and Services',
            ],
            [
                'faculty_id' => '14',
                'first_name' => 'Leah',
                'middle_name' => 'O.',
                'last_name' => 'Pelias',
                'position' => 'Assistant Professor',
                'designation' => 'Associate Dean / Graduate School Head',
                'email' => 'cmndelacruz00774@usep.edu.ph',
                'orcid' => '0000-0002-5279-1268',
                'contact_number' => '(082) 227-8192 local 249',
                'educational_attainment' => 'Bachelor of Science in Information Technology, Master in Information Technology, Doctor in Business Management specialized in Information Systems',
                'field_of_specialization' => 'Multimedia, Design and Development, Identity Management, Recommender System, Business Technology Management',
                'research_interest' => 'Information Systems, Computer Systems Organization, Computer Systems Application',
            ],
            [
                'faculty_id' => '15',
                'first_name' => 'Ariel Roy',
                'middle_name' => 'L.',
                'last_name' => 'Reyes',
                'position' => 'Associate Professor',
                'designation' => null,
                'email' => 'jmmlurzano0057@usep.edu.ph',
                'orcid' => '0000-0001-6234-6099',
                'contact_number' => '(082) 227-8192 local 249',
                'educational_attainment' => 'Bachelor of Science in Computer Engineering, Master\'s in Engineering Program - Electronics and Communications Engineering (MEP-ECE), Doctor in Information Technology (DIT)',
                'field_of_specialization' => 'Computer and Information Security, Computer Networks and Administration, Information Systems Management, Computer Engineering',
                'research_interest' => 'Information Security, Cybersecurity, Computer Network and Security, Cryptography, Authentication Systems',
            ],
            [
                'faculty_id' => '16',
                'first_name' => 'Jamal Kay',
                'middle_name' => 'B.',
                'last_name' => 'Rogers',
                'position' => 'Associate Professor',
                'designation' => 'Deputy Director, ICT Unit (SDMD)',
                'email' => 'jamalkay.rogers@usep.edu.ph',
                'orcid' => '0000-0001-5839-0791',
                'contact_number' => '(082) 227-8192 local 249',
                'educational_attainment' => 'Bachelor of Science in Electronics Engineering, Master of Engineering Program major in Electronics and Communication Engineering',
                'field_of_specialization' => 'Electronics Engineering, Data Science',
                'research_interest' => 'Predictive Analytics, Machine Learning',
            ],
            [
                'faculty_id' => '17',
                'first_name' => 'Francis Andrain',
                'middle_name' => 'S.',
                'last_name' => 'Sanico',
                'position' => 'Instructor',
                'designation' => 'Head, College of Business Administration - LRC',
                'email' => 'francis.sanico@usep.edu.ph',
                'orcid' => null,
                'contact_number' => '(082) 227-8192 local 249',
                'educational_attainment' => 'Bachelor of Library and Information Science, Master of Science in Library and Information Science',
                'field_of_specialization' => 'Management of Libraries, Collection Development, Reference, and Information Services, Indexing and Abstracting, Cataloging and Classification',
                'research_interest' => 'Basic IT in Libraries',
            ],
            [
                'faculty_id' => '18',
                'first_name' => 'Vera Kim',
                'middle_name' => 'S.',
                'last_name' => 'Tequin',
                'position' => 'Instructor',
                'designation' => 'Head, Research and Center Manager, Mindanao Center for Informatics and Intelligent Systems (MCIIS)',
                'email' => 'vkstequin@usep.edu.ph',
                'orcid' => '0009-0006-7409-8989',
                'contact_number' => '(082) 227-8192 local 249',
                'educational_attainment' => 'Bachelor of Science in Computer Science, Master in Information Management',
                'field_of_specialization' => 'Application Development, Database Management, Programming, Database Design and Development',
                'research_interest' => 'Application Development, Database Management, Programming, Database Design and Development',
            ],
            [
                'faculty_id' => '19',
                'first_name' => 'Hermoso',
                'middle_name' => 'J.',
                'last_name' => 'Tupas Jr.',
                'position' => 'Instructor',
                'designation' => null,
                'email' => 'hermoso.tupas@usep.edu.ph',
                'orcid' => '0000-0003-0353-9987',
                'contact_number' => '(082) 227-8192 local 249',
                'educational_attainment' => 'Bachelor of Science in Information Technology, Master in Information Technology',
                'field_of_specialization' => 'Software Development',
                'research_interest' => 'Systems and Informatics, Internet of Things, Disaster Risk and Reduction Management',
            ],
            [
                'faculty_id' => '20',
                'first_name' => 'Maureen',
                'middle_name' => 'M.',
                'last_name' => 'Villamor',
                'position' => 'Professor',
                'designation' => null,
                'email' => 'maui@usep.edu.ph',
                'orcid' => '0000-0001-5051-3646',
                'contact_number' => '(082) 227-8192 local 249',
                'educational_attainment' => 'Bachelor of Science in Computer Science, Master of Science in Information Science, Graduate Diploma in Interaction Design, PhD in Computer Science',
                'field_of_specialization' => 'Computer Science',
                'research_interest' => 'Eye Tracking, Pair Programming, Machine Learning',
            ],
            [
                'faculty_id' => '21',
                'first_name' => 'Philip',
                'middle_name' => 'R.',
                'last_name' => 'Navarez',
                'position' => 'Instructor',
                'designation' => 'PAD and Student Coordinator',
                'email' => 'prnavarez@usep.edu.ph',
                'orcid' => null,
                'contact_number' => '(082) 227-8192 local 249',
                'educational_attainment' => 'Bachelor of Science in Information Technology',
                'field_of_specialization' => 'Web Application Development',
                'research_interest' => 'Web Application Development, IoT, AI',
            ],
            [
                'faculty_id' => '22',
                'first_name' => 'Josephine',
                'middle_name' => 'D.',
                'last_name' => 'Magada',
                'position' => 'Administrative Aide I',
                'designation' => null,
                'email' => 'josephine.magada@usep.edu.ph',
                'orcid' => null,
                'contact_number' => '(082) 227-8192 local 249',
                'educational_attainment' => null,
                'field_of_specialization' => null,
                'research_interest' => null,
            ],
            [
                'faculty_id' => '23',
                'first_name' => 'Marjorie',
                'middle_name' => 'G.',
                'last_name' => 'Inocando',
                'position' => 'MCIIS Staff',
                'designation' => null,
                'email' => 'mginocando@usep.edu.ph',
                'orcid' => null,
                'contact_number' => '(082) 227-8192 local 249',
                'educational_attainment' => null,
                'field_of_specialization' => null,
                'research_interest' => null,
            ],
            [
                'faculty_id' => '24',
                'first_name' => 'Lloyd',
                'middle_name' => 'C.',
                'last_name' => 'Merafuentes',
                'position' => 'Laboratory Aide/Technician',
                'designation' => null,
                'email' => null,
                'orcid' => null,
                'contact_number' => '(082) 227-8192 local 249',
                'educational_attainment' => null,
                'field_of_specialization' => null,
                'research_interest' => null,
            ],
            [
                'faculty_id' => '25',
                'first_name' => 'Kiana',
                'middle_name' => 'G.',
                'last_name' => 'Macan',
                'position' => 'Technical Staff',
                'designation' => null,
                'email' => 'kgmacan@usep.edu.ph',
                'orcid' => null,
                'contact_number' => '(082) 227-8192 local 249',
                'educational_attainment' => null,
                'field_of_specialization' => null,
                'research_interest' => null,
            ],
            [
                'faculty_id' => '26',
                'first_name' => 'Eric',
                'middle_name' => 'P.',
                'last_name' => 'Ricablanca',
                'position' => null,
                'designation' => null,
                'email' => 'epricablanca@usep.edu.ph',
                'orcid' => null,
                'contact_number' => null,
                'educational_attainment' => null,
                'field_of_specialization' => null,
                'research_interest' => null,
            ],
            [
                'faculty_id' => '27',
                'first_name' => 'Michael Anthony',
                'middle_name' => 'R.',
                'last_name' => 'Jandayan',
                'position' => null,
                'designation' => null,
                'email' => 'michaelanthony.jandayan@usep.edu.ph',
                'orcid' => null,
                'contact_number' => null,
                'educational_attainment' => null,
                'field_of_specialization' => null,
                'research_interest' => null,
            ],
            [
                'faculty_id' => '28',
                'first_name' => 'Franch Maverick',
                'middle_name' => 'A.',
                'last_name' => 'Lorilla',
                'position' => null,
                'designation' => null,
                'email' => 'franch@usep.edu.ph',
                'orcid' => null,
                'contact_number' => null,
                'educational_attainment' => null,
                'field_of_specialization' => null,
                'research_interest' => null,
            ],
            [
                'faculty_id' => '29',
                'first_name' => 'Val',
                'middle_name' => 'A.',
                'last_name' => 'Quimno',
                'position' => null,
                'designation' => null,
                'email' => 'val@usep.edu.ph',
                'orcid' => null,
                'contact_number' => null,
                'educational_attainment' => null,
                'field_of_specialization' => null,
                'research_interest' => null,
            ],
            [
                'faculty_id' => '30',
                'first_name' => 'Maychelle',
                'middle_name' => 'M.',
                'last_name' => 'Nugas',
                'position' => null,
                'designation' => null,
                'email' => 'maychellenugas@usep.edu.ph',
                'orcid' => null,
                'contact_number' => null,
                'educational_attainment' => null,
                'field_of_specialization' => null,
                'research_interest' => null,
            ],
        ];

        foreach ($faculties as $facultyData) {
            Faculty::updateOrCreate(
                ['email' => $facultyData['email']],
                $facultyData
            );
        }
    }
}