<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Str;
use App\Models\Keyword;

class KeywordSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $keywords = [
            'Traffic citations',
            'Double encoding',
            'Traffic ticket issuance',
            'Web-based record system',
            'Driver\'s license scanning',
            'Traffic management',
            'Ultrasonic sensor',
            'Fish disease',
            'Fish farm management',
            'Automated detection system',
            'Water contamination',
            'Mortality rate monitoring',
            'Laptops and smartphones',
            'Economically marginalized students',
            'Programming logic',
            'Mobile IDE',
            'OCR technology',
            'Executable scripts',
            'Classroom distractions',
            'Mobile device usage',
            'VOIP-enabled application',
            'Hybrid voice distribution',
            'Dynamic Systems Development Method (DSDM)',
            'Cordova framework',
            'Real-time voice broadcasting',
            'Asthma monitoring',
            'Wearable device',
            'Heart rate tracking',
            'Geo-tagging',
            'Chronic disease control',
            'Lung function monitoring',
            'Smartphone sensors',
            'Gas leak detection',
            'Fire prevention',
            'Arduino-based LPG sensor',
            'Aerofree app',
            'Rapid Application Development (RAD)',
            'Community safety awareness',
            'Real-time notifications',
            'Breastmilk donation',
            'Breastfeeding culture',
            'Milk-sharing platform',
            'GPS-based donor matching',
            'Postpartum support',
            'Mother and child health',
            'Road traffic accidents',
            'Pedestrian and driver safety',
            'Human error in accidents',
            'Mobile alert system',
            'Accident-prone areas',
            'Speed limit awareness',
            'Traffic safety technology',
            'Traffic congestion',
            'Traffic violations',
            'Mobile-based application',
            'Live video feed',
            'Real-time location tracking',
            'Traffic enforcement technology',
            'Ionic Framework and Java',
            'Dyslexia intervention',
            'Learning disability',
            'Educational learning application',
            'Cognitive and psychomotor activities',
            'Early childhood education',
            'R.A.S.E. Model',
            'Mobile learning technology',
            'Heatwave prevention',
            'Heatstroke and heat exhaustion',
            'Body temperature monitoring',
            'Wearable cooling device',
            'Real-time mobile application',
            'Peltier module technology',
            'Heat protection',
            'Copra drying automation',
            'Artificial drying machine',
            'Moisture content monitoring',
            'Web-based monitoring system',
            'Traditional vs. artificial drying',
            'Quality control in copra production',
            'Small-scale coconut farmers',
            'Palay bidding',
            'Rice law impact',
            'Direct market',
            'Scrum method',
            'Digital trade',
            'No middlemen',
            'Rice pest detection',
            'Stem borer & leaf blast',
            'Farmer assistance',
            'Mobile solution',
            'Integrated pest management',
            'Improved crop yield',
            'Accurate treatment',
            'Agile development cycle',
            'Agile software development',
            'Amperes',
            'Android Studio',
            'Arduino',
            'Arduino current sensor',
            'Arduino IDE',
            'ARIMA model',
            'Assistive technology',
            'Automatic trap',
            'Autism Spectrum Disorder',
            'Braille',
            'BPM',
            'Camera',
            'Circuit breaker',
            'Circuit overloading',
            'Cloud database',
            'Communicative openness',
            'Conductance',
            'Contracted Braille (Grade 2)',
            'Crime density mapping',
            'Crime incident',
            'Crowdsourced market data',
            'Decibel analysis',
            'Digital Image Processing',
            'DO sensors',
            'ESP32-cam',
            'ESP8266',
            'Eye blink sensor',
            'Filtration media',
            'Fish mortality',
            'Flood levels',
            'Flood monitoring',
            'Food donors',
            'Food waste awareness',
            'Food waste prevention',
            'Freshwater',
            'Freshwater environment',
            'Fuzzy logic method',
            'Galvanic Skin Response (GSR)',
            'agricultural commodities',
            'Davao Food Terminal Complex',
            'transaction tracking',
            'security',
            'Two-Factor Authentication',
            'data encryption',
            'Online reservation',
            'hotel industry',
            'fraud prevention',
            'identity theft',
            'user verification',
            'ratings',
            'feedback system',
            'SSL certification',
            'IoT',
            'pig cough detection',
            'respiratory diseases',
            'African Swine Fever',
            'machine learning',
            'biosecurity',
            'real-time monitoring',
            'Smishing',
            'malicious URLs',
            'SMS phishing',
            'mobile security',
            'blacklist database',
            'real-time detection',
            'coffee startups',
            'Davao City',
            'market access',
            'brand building',
            'inventory management',
            'digital transformation',
            'demand forecasting',
            'food retailers',
            'Simple Moving Average',
            'restock planning',
            'sales data analysis',
            'Data privacy',
            'cybersecurity',
            'game-based learning',
            'teenagers',
            'awareness',
            'digital security',
            'serious games',
            'Privacy Impact Assessment',
            'web-based assessment tool',
            'Risk assessment',
            'Decision support',
            'QR code security',
            'phishing attacks',
            'Google Safe Browsing',
            'VirusTotal API',
            'Employee attrition',
            'predictive analytics',
            'Random Forest Algorithm',
            'HR management',
            'visualization',
            'Public transportation',
            'real-time tracking',
            'jeepneys',
            'seat vacancy',
            'commuter assistance',
            'mobile application',
            'Rice farming',
            'nitrogen fertilization',
            'Leaf Color Chart',
            'RGB color extraction',
            'KNN Algorithm',
            'weather forecasting',
            'Personal aliasing',
            'data security',
            'identity protection',
            'secure login',
            'browser extension',
            'Event planning',
            'SMEs',
            'web-based platform',
            'customer-to-customer marketing',
            'SCRUM methodology',
            'service promotion',
            'Construction waste',
            'demolition recycling',
            'marketplace',
            'geotagging',
            'CCD waste',
            'environmental sustainability',
            'Augmented Reality',
            'wayfinding',
            'intellectual disability',
            'navigation',
            'simulation-based learning',
            'Google API',
            'crop bidding',
            'small-scale farmers',
            'authentication',
            'SMS OTP',
            'Mental health',
            'self-monitoring',
            'diary app',
            'journaling',
            'mental illness',
            'emotional well-being',
            'electricity theft detection',
            'smart meter',
            'energy security',
            'Basketball analytics',
            'coach decision-making',
            'sports technology',
            'Programming education',
            'student engagement',
            'boredom detection',
            'frustration analysis',
            'keystrokes',
            'mouse movements',
            'Climate change',
            'cacao farming',
            'neural network modeling',
            'land suitability',
            'future climate projections',
            'Motorcycle Theft',
            'Property Crime',
            'SNAPDRIVE',
            'Hardware',
            'Software',
            'Raspberry Pi',
            'Motion Detection',
            'Facial Detection',
            'Haar Cascade',
            'Eye Blink Detection',
            'Facial Landmark',
            'Image Capture',
            'Facial Recognition',
            'Sparse Local Binary Pattern Histogram',
            'Cloud Server',
            'DC Motor',
            'Security System',
            'Crime Prevention',
            'Waterfall Methodology',
            'E-commerce',
            'Traditional Keyword-Based Search',
            'Semantic Searching',
            'Data Retrieval',
            'Context',
            'Intent',
            'Natural Language Processing (NLP)',
            'Semantic Search Engine',
            'Elasticsearch',
            'Amazon Dataset',
            'Flask',
            'Ngrok',
            'Web Application',
            'False Positives',
            'Search Accuracy',
            'Product Categorization',
            'Ontologies',
            'Fake News',
            'Coronavirus',
            'COVID-19',
            'Hybrid Algorithm',
            'Twitter',
            'Philippines',
            'Boxing',
            'Boxers',
            'Coaches',
            'Training Plans',
            'Historical Data Analysis',
            'Match Prediction',
            'Winning Conditions',
            'SVM Algorithm',
            'K-Means Clustering',
            'CompuBox Data',
            'Accuracy',
            'F1-Score',
            'Unbalanced Dataset',
            'Clustering Model',
            'Boxing Styles',
            'Swarmer',
            'Slugger',
            'Outboxer',
            'Performance Improvement',
            'Winning Tactics',
            'Sea Level Rise',
            'Coastal Communities',
            'Predictive Model',
            'Random Forest Regression',
            'Data Attributes',
            'Feature Selection',
            'Feature Engineering',
            'Feature Scaling',
            'Hyperparameter Tuning',
            'Model Performance',
            'R-Squared Score',
            'Mean Absolute Error (MAE)',
            'Mean Squared Error (MSE)',
            'Root Mean Squared Error (RMSE)',
            'Greenhouse Gases',
            'Carbon Dioxide',
            'Methane',
            'Prediction',
            'Year 2100',
            'R Shiny',
            'Interactive Visualization',
            'Coastal Areas',
            'Google Earth',
            'Data Collection',
            'Accuracy Improvement',
            'Fisheries',
            'Anthropogenic Risks',
            'Oceanic Destruction',
            'Weather Changes',
            'Fish Shoals',
            'High Cost',
            'Low Profit',
            'Socio-Economic Status',
            'Potential Fishing Zones (PFZs)',
            'Sea Features',
            'Predictors',
            'Fish Catch Forecasting',
            'Seasonal Fish Catch Behavior',
            'Feature Importance',
            'Classification Machine Learning',
            'Secondary Data',
            'Visayan Sea',
            'India',
            'ARIMA',
            'Salinity',
            'Sea Chlorophyll',
            'Random Forest',
            'Accuracy Score',
            'Threshold Values',
            'AIC Value',
            'Forecasting',
            'Fish Catch Seasonality',
            'Resource Management',
            'Uncertainties',
            'Fishing Community',
            'Aquaculture Industry',
            'Aquatic Products',
            'Human Population Growth',
            'Fish Health',
            'Water Quality',
            'Temperature',
            'pH Level',
            'Stress in Fish',
            'Aquaculture Management',
            'Yield Reduction',
            'Financial Loss',
            'Machine Learning Models',
            'SVM (Support Vector Machine)',
            'KNN (K-Nearest Neighbors)',
            'Decision Tree Algorithm',
            'GridSearchCV',
            'Prediction Models',
            'Breast Cancer',
            'Filipino Women',
            'Mammography',
            'Self-Examinations',
            'Artificial Intelligence (AI)',
            'Diagnostic Precision',
            'Prognosis',
            'Survival Rates',
            'Hybrid Model',
            'Cancerous Cell Segmentation',
            'Breast Mammogram Images',
            'ResNet-152',
            'Nested UNet (UNet++)',
            'Intersection Over Union (IOU)',
            'DICE Score',
            'Binary Cross Entropy',
            'Pre-Processing',
            'Data Augmentation',
            'Hyperparameters',
            'Fine-Tuning',
            'Model Accuracy',
            'Overfitting',
            'Underfitting',
            'Pathological Ground Truth Masks',
            'Banana Maturity',
            'Marketability',
            'Growers',
            'Classification Models',
            'Training Time',
            'Model Efficiency',
            'Transfer Learning',
            'ResNet-18 Architecture',
            'Cavendish Banana',
            '10-Fold Cross-Validation',
            'CNN-Based Model',
            'Unseen Data',
            'Locally Sourced Dataset',
            'Fruit Classification',
            'Población District',
            'Barangays',
            'Local Government',
            'Health Care Programs',
            'Drug Prevention',
            'Rehabilitation',
            'Neural Networks',
            'Dense Layer',
            'Substance Abuse',
            'Adolescents',
            'Graphical Analysis',
            'Geographic Maps',
            'Statistical Reports',
            'Gender Ratio',
            'Age Groups',
            'Trend Analysis',
            'Decision-Making',
            'Proactive Measures',
            'Durian',
            'King of Fruits',
            'Southeast Asia',
            'Durian Industry',
            'Post-Harvest Losses',
            'Durian Diseases',
            'Visual Inspection',
            'DurI0-an',
            'Durio Zibethinus',
            'RGB + UNet',
            'GLCM + UNet',
            'RGB + GLCM + UNet',
            'IoU Score',
            'Early Detection',
            'Wilcoxon Signed Rank Test',
            'Severity Index Estimation',
            'Agricultural Technology',
            'Cryptocurrency',
            'Financial Investment',
            'Volatility',
            'Automated Trading',
            'Ensemble Learning',
            'Trading Bot',
            'Bitcoin',
            'Binance',
            'Ethereum',
            'Bagging',
            'Boosting',
            'Stacking',
            'Base Learner Models',
            'Naïve-LR-NBeats',
            'ARIMA-NBeats',
            'LR-NBeats',
            'Buy-Low-Sell-High Strategy',
            'Backtesting',
            'Simulations',
            'Swing Trading',
            'Investment Returns',
            'Win-Loss Ratios',
            'Algorithm',
            'Trading Strategies',
            'Classical Statistical Models',
            'Fish Production',
            'Fishing Techniques',
            'Davao Gulf',
            'Geospatial Data Science',
            'Sea Surface Temperature (SST)',
            'Thermal Front',
            'Sea Surface Chlorophyll-a Concentration (SSCC)',
            'Interpolation Models',
            'Universal Kriging',
            'Simple Additive Weighting (SAW)',
            'Dashboard Application',
            'Fishing Efficiency',
            'Academic Libraries',
            'Accessibility',
            'Accessibility Accommodations',
            'ADDIE Model',
            'Analytic',
            'Archiving and Metadata Management',
            'Assistive Learning Tool',
            'Book Collection Reports',
            'Book Ordering and Exhibiting System',
            'Career Aspirations',
            'Chat',
            'Collection Mapping',
            'Community Engagement',
            'Competency Level',
            'Conspectus',
            'Copyright',
            'COVID-19 Pandemic',
            'Critical Appraisal',
            'Cultural Heritage Preservation',
            'Curriculum Development',
            'Data Visualization',
            'Davao Region Libraries',
            'Design Prototype',
            'Digital Learning Support',
            'Digital Library System',
            'Digital Repository System',
            'Digital Rights Management',
            'Enhanced Reading Program',
            'Evidence-Based Medicine',
            'Feature Suggestions',
            'Filipino Language for Foreign Students',
            'Fair Use',
            'Functionality Testing and User Evaluation',
            'Graphical Representation of Library Resources',
            'Health Sciences Librarian',
            'Higher Education',
            'Historical and Cultural Artifacts',
            'Human Resource Capability',
            'Inclusive Libraries',
            'Inclusive Library Services',
            'Indexinator',
            'Information and Computing Students',
            'Institutional Digital Repository',
            'Intellectual Property',
            'Interactive Learning System',
            'Interactive Resource Sharing Platform',
            'Librarian Competencies',
            'Librarians\' Preferences',
            'Library Accommodations',
            'Library and Information Science',
            'Library Collection Assessment',
            'Library Marketing',
            'Library Modifications',
            'Library Online Access',
            'Library Programs',
            'Library Resources',
            'Library Service Delivery',
            'Library Service Design Model',
            'Library Services',
            'Lived Experiences',
            'Mandaya-English Translation',
            'Marketing Strategies',
            'Mixed-Methods Research',
            'Modified Iterative and Incremental Development (IID)',
            'Modified Rapid Application Development (RAD)',
            'Multi-Channel Support (Chat, Email, Web Form)',
            'ODILO database',
            'Offline Translation System',
            'Online Library Book Fair',
            'Online Library Services',
            'Online Survey',
            'Personal Skill Set',
            'PHP and MySQL-Based System',
            'PLAI-DRLC Library Consortium',
            'Professional Core Competency',
            'Public Library',
            'Public School Libraries',
            'Quantitative Descriptive Study',
            'Reading Comprehension',
            'Remote Access',
            'Ren\'py Visual Novel Engine',
            'Resource Sharing',
            'School Library',
            'Skill Assessment',
            'Social Acceptability',
            'Special Needs Patrons',
            'Speech, Photo, and Audio Integration',
            'Student Motivation',
            'System Development Life Cycle (SDLC) - Spiral Model',
            'System Development Life Cycle (SDLC) - Waterfall Model',
            'TAM',
            'Text, Photo, and Audio Integration',
            'Three-Phase Development Strategy',
            'University Museum',
            'University of Southeastern Philippines',
            'University of the Immaculate Conception',
            'User Acceptance Level',
            'User Acceptance Testing and Evaluation',
            'Utilization',
            'UVDesk and MySQL Integration',
            'Vocational Education',
            'Web Portal Design',
            'Web-Based Indexing Tool',
            'Web-Based Support Service Ticketing System',
            'Youth Development',
        ];

        foreach ($keywords as $keyword) {
            Keyword::updateOrCreate(
                ['keyword_name' => $keyword],
                ['keyword_name' => $keyword]
            );
        }
    }
}
